Домашнее задание 1
Ivanova-Ekaterina/2018-FS-11-Frontend-Ivanova-Ekaterina pull request #1
Opened 2018-10-10 18:36 UTC by Ivanova-Ekaterina

Изменила функцию say(/src/lib/test.js) чтобы она создавала блок с фоном и текстом

2018-10-10 18:39 UTC, martinkomitsky requested changes
Исправить замечание и сделать последний пункт ДЗ про ESLint.

2018-10-10 18:39 UTC, martinkomitsky commented on src/lib/test.js
> +  elem.style.height = '100px';
Стили вынести в css файл, в этом месте вместо добавления отдельно этих свойств, назначить соответствующий css class

2018-10-10 18:46 UTC, Ivanova-Ekaterina commented on src/lib/test.js
> +  elem.style.height = '100px';
А какие файлы нужно для последнего пункта добавлять?

2018-10-10 19:54 UTC, martinkomitsky commented on src/lib/test.js
> +  elem.style.height = '100px';
Для какого последнего пункта?

2018-10-10 20:58 UTC, martinkomitsky requested changes
Если eslint выдает ошибки, надо их исправить. 

Про document можно починить так:
https://eslint.org/docs/2.0.0/user-guide/configuring
```
{
    "name": "mypackage",
    "version": "0.0.1",
    "eslintConfig": {
        "env": {
            "browser": true
        }
    }
}
```

2018-10-11 21:52 UTC, martinkomitsky approved these changes

2018-10-11 21:52 UTC, merged

2018-10-11 21:53 UTC, martinkomitsky commented
10