hw1
Ivanova-Ekaterina/2018-FS-11-Frontend-Ivanova-Ekaterina pull request #11
Opened 2019-04-08 00:36 UTC by Ivanova-Ekaterina

Добавила emoji

2019-04-08 19:56 UTC, martinkomitsky requested changes

2019-04-08 19:56 UTC, martinkomitsky commented on webpack.config
> +const path = require('path');
У тебя добавлен внешний вебпак зачем-то. 

Для начала, тебе надо сделать `npm run eject`, чтобы стал доступен для редактирования конфиг create-react-app. И свою примочку для спрайтов надо будет перенести туда.

2019-04-08 19:56 UTC, martinkomitsky commented on package.json
> +    "@webpack-cli/init": "^0.1.5",
вебпак надо будет удалить, и webpack-cli тоже. Его надо достать при помощи npm run eject и там править

2019-04-08 20:59 UTC, Ivanova-Ekaterina commented on webpack.config
> +const path = require('path');
Исправила

2019-04-13 07:28 UTC, martinkomitsky commented on webpack.config
> +const path = require('path');
Не совсем) ты сделала eject и потом удалила webpack, надо было сделать наоборот. Впрочем, я вернул твои вебпаки, потому что не мог запустить проект)

2019-04-13 07:29 UTC, martinkomitsky approved these changes

2019-04-13 07:29 UTC, merged

2019-04-13 07:29 UTC, martinkomitsky commented
6