Hw3
Ivanova-Ekaterina/2018-FS-11-Frontend-Ivanova-Ekaterina pull request #4
Opened 2018-10-24 20:13 UTC by Ivanova-Ekaterina

При отправке общений они добавляются в форму
При добавлении изображения, отправляется миниатюра, для других файлов просто пишется url
Не получилось прикрепить в форме ввода значок для файлов(работает только с абсолютным путем, не могу понять какой нужно указать, чтоб все нормально было)
Еще с прокруткой сообщений не до конца понятно, при включении overflow полоса появляется и все(

2018-10-26 17:46 UTC, martinkomitsky commented
Можно, все-таки, вернуть имя в название репозитория? Я опять чуть не спутал тебя с Натальей Ивановой.
![image](https://user-images.githubusercontent.com/14847018/47583441-270c3780-d960-11e8-9b0b-8e1f1bc0a4bc.png)

2018-10-30 19:41 UTC, martinkomitsky commented
Спасибо большое за смену имени))

2018-10-30 19:50 UTC, martinkomitsky commented on src/lib/components/message-form/shadow.css
> +	background-image: url(/home/ekaterina/tt_front/src/lib/img/attachment_24_px.svg);
Нельзя писать такие пути, у меня, например, нет на компе папки "ekaterina".

Для того, чтобы статика (картинки) отображалась, они должны тоже попадать в папку dist. Вероятно, надо настроить какой-то `loader` в `webpack` для того, чтобы он все такие файлы туда складировал, а уже в результирующей сборке из `.html` был до этого места доступ.
![image](https://user-images.githubusercontent.com/14847018/47745880-c77e9680-dc95-11e8-9788-e5f25fb3a584.png)

2018-10-30 19:56 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/47746205-bd10cc80-dc96-11e8-99ca-d34419c57188.png)
Для того, чтобы твой скролл заработал, оберни `div.messages` в еще один `div` (который я на скриншоте назвал `div.scroll` и ему назначь эти свойства: `overflow: scroll; height: 500px;`, а аналогичные из `div.messages` убери.

2018-10-31 17:18 UTC, Ivanova-Ekaterina commented
Иправила scroll
Добавила геопозицию и drag&drop

2018-11-02 11:44 UTC, Ivanova-Ekaterina commented
Вроде получилось нормально прикрепить картинки, на геопозиции пока иконка поиска)

2018-11-04 07:32 UTC, martinkomitsky approved these changes

2018-11-04 07:32 UTC, martinkomitsky commented
Нрайца, 10

2018-11-04 07:32 UTC, merged